In [167]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

In [229]:
df = pd.read_csv("house_price.csv")
df.shape
print(df.shape)
print(df["SalePrice"].isna().sum())
df.head()
df.drop(['Id'],axis=1,inplace=True)
df['SalePrice'] = df['SalePrice'].fillna(df['SalePrice'].mean()) 
# Drop records with null values
df = df.dropna()
df.isnull().sum()
df.head()

(2919, 13)
1459

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [230]:
# Data Preprocessing - Encoding (Covered in Supervised ML Part2)
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
df = pd.get_dummies(df, columns=cols, drop_first=True)

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     2919 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [232]:
# Train-Test Split
from sklearn.model_selection import train_test_split

X = df.drop(['SalePrice'], axis=1)
Y = df['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0)

In [234]:
# Train Linear Regression Model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [233]:
df.describe()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000,2913.000000
mean,57.190182,10137.665980,5.566770,1971.391349,1984.314452,49.667353,1052.805012,180921.195890
std,42.538067,7832.598853,1.108977,30.258751,20.864950,169.338330,439.688510,56232.174632
min,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,20.000000,7476.000000,5.000000,1954.000000,1965.000000,0.000000,793.000000,163000.000000
50%,50.000000,9450.000000,5.000000,1973.000000,1993.000000,0.000000,990.000000,180921.195890
75%,70.000000,11553.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,180921.195890
max,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [238]:
# Model Evaluation
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print(mean_absolute_percentage_error(y_test, y_pred))

R2 Score: 0.374142179613837
MAE: 30829.936664322195
RMSE: 41138.55870230158
0.18742025463428158

In [237]:
# plt.scatter(df["LotArea"], df["SalePrice"])
# plt.xlabel("Lot Area")
# plt.ylabel("Sale Price")
# plt.show()

In [187]:
# plt.scatter(df["YearBuilt"], df["SalePrice"])
# plt.xlabel("Year Built")
# plt.ylabel("Sale Price")
# plt.show()

In [188]:
# df[["YearBuilt", "SalePrice"]].corr()

In [189]:
# plt.scatter(df["TotalBsmtSF"], df["SalePrice"])
# plt.xlabel("Total Basement Area")
# plt.ylabel("Sale Price")
# plt.show()

In [190]:
# import seaborn as sns

# sns.boxplot(x="MSZoning", y="SalePrice", data=df)
# plt.xticks(rotation=45)
# plt.show()

In [191]:
# sns.boxplot(x="BldgType", y="SalePrice", data=df)
# plt.show()

In [192]:
# sns.boxplot(x="OverallCond", y="SalePrice", data=df)
# plt.show()

In [193]:
df =df.dropna()#drop row missing

In [194]:
# df["YearsSinceRemodel"] = df["YearRemodAdd"] - df["YearBuilt"]

In [195]:
# plt.scatter(df["YearRemodAdd"], df["SalePrice"])
# plt.show()

In [196]:
X = df.drop(columns=["Id","Exterior1st", "BldgType", "LotConfig", "MSZoning","SalePrice"])

In [197]:
X

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,60,8450,5,2003,2003,0.0,856.0
1,20,9600,8,1976,1976,0.0,1262.0
2,60,11250,5,2001,2002,0.0,920.0
3,70,9550,5,1915,1970,0.0,756.0
4,60,14260,5,2000,2000,0.0,1145.0
...,...,...,...,...,...,...,...
2914,160,1936,7,1970,1970,0.0,546.0
2915,160,1894,5,1970,1970,0.0,546.0
2916,20,20000,7,1960,1996,0.0,1224.0
2917,85,10441,5,1992,1992,0.0,912.0
2918,60,9627,5,1993,1994,0.0,996.0

In [198]:
y = df["SalePrice"]

In [199]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [200]:
X_train

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
2356,20,7441,5,2006,2006,0.0,1461.0
1789,30,10800,5,1890,1998,0.0,630.0
2371,20,7321,5,1999,2000,0.0,1339.0
930,20,8925,5,2007,2007,0.0,1466.0
2816,20,13050,6,1963,1963,850.0,1000.0
...,...,...,...,...,...,...,...
1638,20,10928,6,1978,1986,0.0,1427.0
1095,20,9317,5,2006,2006,0.0,1314.0
1130,50,7804,3,1928,1950,0.0,1122.0
1294,20,8172,7,1955,1990,0.0,864.0
860,50,7642,8,1918,1998,0.0,912.0

In [201]:
y_train

2356    180921.19589
1789    180921.19589
2371    180921.19589
930     201000.00000
2816    180921.19589
            ...
1638    180921.19589
1095    176432.00000
1130    135000.00000
1294    115000.00000
860     189950.00000
Name: SalePrice, Length: 2330, dtype: float64

In [202]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [203]:
y_pred = model.predict(X_test)

In [204]:
print("Actual:")
print(y_test.head(10))

print("\nPredicted:")
print(y_pred[:10])

Actual:
178     501837.00000
678     372500.00000
2878    180921.19589
2691    180921.19589
1898    180921.19589
2173    180921.19589
729     103000.00000
450     110000.00000
1736    180921.19589
2360    180921.19589
Name: SalePrice, dtype: float64

Predicted:
[249213.86170395 236162.1435243  153739.31457123 197257.23219342
 166937.40290374 202687.39472464 136836.7696516  169615.41271953
 227724.92865174 173360.71306332]

In [205]:
print(y_test.shape)
print(y_pred.shape)

(583,)
(583,)

In [206]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print("adjusted r^2:",adjusted_r2)

R2: 0.3231929169904396
MAE: 32954.80905019967
MSE: 2467685470.610117
adjusted r^2: 0.5697429725330359

In [207]:
df = pd.read_csv("house_price.csv")
df.shape
print(df.shape)
print(df["SalePrice"].isna().sum())
df.head()
df["BldgType"].nunique()
df =df.dropna()#drop row missing
df
X = df.drop(columns=["Id","Exterior1st", "LotConfig", "MSZoning","SalePrice"])

(2919, 13)
1459

In [215]:
X = df.drop(['SalePrice'], axis=1)
y = df['SalePrice']

In [216]:
cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
X = pd.get_dummies(df, columns=cols, drop_first=True)

In [210]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

In [211]:
X.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0.0,856.0,208500.0,False,...,False,False,False,False,False,False,False,True,False,False
1,1,20,9600,8,1976,1976,0.0,1262.0,181500.0,False,...,False,False,False,True,False,False,False,False,False,False
2,2,60,11250,5,2001,2002,0.0,920.0,223500.0,False,...,False,False,False,False,False,False,False,True,False,False
3,3,70,9550,5,1915,1970,0.0,756.0,140000.0,False,...,False,False,False,False,False,False,False,False,True,False
4,4,60,14260,5,2000,2000,0.0,1145.0,250000.0,False,...,False,False,False,False,False,False,False,True,False,False

In [217]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [218]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [219]:
y_pred = model.predict(X_test)

In [220]:


print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print("adjusted r^2:",adjusted_r2)

R2: 1.0
MAE: 1.0014408784727119e-10
MSE: 2.261588847160599e-20
adjusted r^2: 0.5168011898564369